Workaround out of range time
Querying the inverter can fail with

  ValueError: hour must be in 0..23

This was due to discharge_slot_1 being 2400 instead of 0. Workaround this
issue by forcing value to 0 if its greater than or equal to 2400

Signed-off-by: Martin Bark <martin@barkynet.com>